### ISSUE TITLE
Request: using Graphviz Python package instead of Graphviz installation

### ISSUE THREAD

**Issue by SarazinMAC** [scottrogowski/code2flow#106]
Hi there, I work for a government organisation where we have heavily managed laptops, where we only have security clearance for installing a very limited set of software. I note that there is a Python package for Graphviz (which we have access to). Would it be possible to use this package to create the graphs in code2flow, instead of the Graphviz local installation? Thanks for considering our request!

**Comment by patfinder** [comment]
Hi @SarazinMAC,
As far as I know, currently you need both Graphviz python package and Graphviz binary (Graphviz local installation) for this app to work. As the [document said](PyGraphviz is a Python interface to the Graphviz graph layout and visualization package), pgraphviz python is "a Python interface to the Graphviz".
So in summary, the answer is "No" for your question.

BTW, I am NOT the creator of this tool, just an independent developer.

**Comment by patfinder** [comment]
Also, If you can use docker then you can install/download the executable and this tool on that docker container and execute it in an isolated environment.

**Comment by patfinder** [comment]
Hi @SarazinMAC 

The PR [here](https://github.com/scottrogowski/code2flow/pull/107) might be interesting to you.

**Comment by SarazinMAC** [comment]
Thanks - very helpful!

**Comment by KeilanEvans** [comment]
For anyone that might be interested, I have released a version with Graphviz installed. The repo can be found at https://github.com/KeilanEvans/code2flowdiagram and the package can be installed with pip install code2flowdiagram. All credit goes to the owner of this repo, I merely added the binaries and changed the code to use them
