### ISSUE TITLE
Request for PHP support

### ISSUE THREAD

**Issue by klaernie** [scottrogowski/code2flow#12]
From my experience I have seen the messiest code written in PHP. Hence I'd like to see support for PHP.

What do you think is required to implement a new language in code2flow?

**Comment by scottrogowski** [comment]
Hi klaernie. Sorry to keep you waiting. I'm no longer developing code2flow but if you wanted to do it yourself, you should be able to subclass engine.py. You can looks to languages/javascript.py & languages/python.py for examples

**Comment by SehgalDivij** [comment]
Anyway to Generate Stuff Like this for a Django Application?

**Comment by scottrogowski** [comment]
You could try something like `code2flow project/project/*.py`

see https://github.com/scottrogowski/code2flow#usage

**Comment by SehgalDivij** [comment]
The Above Command gave me this:
https://transfer.sh/Yktfb/code2flow_out.png
Tried this on a single views.py file and it worked fine.
What I actually need is something to generate a logical view of what is going on in the application when a request is made, i.e, URL request -> Passes thorugh various middlewares -> Passes through a View in views,py -> calls other user defined functions -> that in turn call other functions within the Application.

**Comment by scottrogowski** [comment]
Hi all, this is a bit late but I'm now under contract to add PHP support over the coming weeks.

Separately, the project has been completely rewritten so it also might be worth trying Django again.

**Comment by vdanielpop** [comment]
Hi @scottrogowski , sorry to ping you on such an old issue.

First of all, thanks a lot for building this, it looks amazing!
I was playing around with it on a Symfony 5 project of mine and , while it succesfully maps the relations within a single file, it seems to have some problems when it comes to namespaces. I believe it fails to map the namespace to the actual location of the file (which I do not expect to work out of the box, but I also did not find a way to pass it as arguments). This is part of the terminal output:
![419618385_1084963309197196_8434246863310662571_n](https://github.com/scottrogowski/code2flow/assets/5840350/e02488fe-c06e-428d-b42e-fdf17cb1e45f)


Could you tell me if this is something that just doesn't work at the moment or if I missed something?

Thank you!
