### ISSUE TITLE
TypeScript Support

### ISSUE THREAD

**Issue by Tiberriver256** [scottrogowski/code2flow#14]
This is awesome!

Any thoughts on adding support for TypeScript?

**Comment by scottrogowski** [comment]
Sorry. I didn't have notifications running for this project but am maintaining it again. I would love to add typescript support but if I'm being honest, I don't have the bandwidth. The code should be far more readable now if anyone wants to take a look and give it a shot. I'm currently under contract to add JS, Ruby, and PHP again.

**Comment by roehst** [comment]
Is this task alive/dead as of 2025? I tried to use Code2flow w/ TSX/TS and I am trying to work on a solution.
