### ISSUE TITLE
Tracing through many files and modules

### ISSUE THREAD

**Issue by luggie** [scottrogowski/code2flow#20]
I don't know if I use this program wrong but when I try to generate a call graph for a (bigger) package, I call `code2flow main.py`. But then the graph ends in `main.py` even though it calls many other modules within the same package/directory. When adding many `.py` files that also call upon each other, code2flow simply creates separated graphs in one file for each file. Is this what the programs is supposed to do or am I doing doing it wrong?

**Comment by scottrogowski** [comment]
Hi @luggie. Sorry to get back to you so late. I've not had notifications running for this project. The code was out of date and it has now been rewritten. So I can't speak to how it was before but feel free to try again.
