### ISSUE TITLE
sequence diagram visualization

### ISSUE THREAD

**Issue by ibrahimsk1** [scottrogowski/code2flow#21]
it will be nice if there is an sequence diagram visualization option.

this diagram represent one main function in DOT flowcharts and it will be more readable i guess.

![image](https://user-images.githubusercontent.com/35404031/115043602-58d13a00-9edd-11eb-84bb-98e862738211.png)

**Comment by scottrogowski** [comment]
Hi @ibrahimsk1. There is one main problem this. Code2flow generates graphs which can be cyclic (e.g. a() can call b() which can call a()). This would be hard to represent on this sort of diagram. Happy to hear ideas if you have them because I agree that the diagrams can be difficult to read.

**Comment by scottrogowski** [comment]
Closing for now. Feel free to reopen if you have an idea
