### ISSUE TITLE
fill-color for regular function

### ISSUE THREAD

**Issue by suetsuguk** [scottrogowski/code2flow#22]
As highlighted in red rectangle in the bellow image, fill-color for regular function is inconsistent.
Seen from the [code](https://github.com/scottrogowski/code2flow/blob/8e4154b81a77477fa86d3b4459e6f2a1b143525d/lib/model.py#L260-L263), the `fillcolor` property is not set for regular function, so the default color (light gray?) seems to be used.
I prefer filling it in light gray. What do you think?

![image](https://user-images.githubusercontent.com/36753697/118913235-006ddc00-b964-11eb-89cc-2864166a80dd.png)

**Comment by scottrogowski** [comment]
Agree. This was an oversight on my part. Fixed.
