### ISSUE TITLE
[Feature request] Graphing jQuery calls

### ISSUE THREAD

**Issue by ChristopherRabotin** [scottrogowski/code2flow#3]
This might be a tough feature, yet it would be exceptionally useful if available. jQuery calls start with a dollar sign, or with (jQuery) with the parenthesis if used in non-conflict mode (iirc). That's where a lot of drawing is done.

I could give it a shot when I find some time.

**Comment by scottrogowski** [comment]
Hi all,

I'm addressing this issue 8 years later. I have rewrote code2flow and just merged the Python branch into master. The javascript rewrite will also soon be merged. It uses ASTs internally so I suspect it will work a lot better with validly named javascript tokens.

**Comment by ChristopherRabotin** [comment]
I had totally forgotten about your project, so thanks for the heads up. I think this can be very helpful for a project I'm currently working on.

**Comment by scottrogowski** [comment]
Glad to hear it might still be helpful! I'll let you know when I finish the javascript rewrite. It might be a few weeks still
