### ISSUE TITLE
Request: New Shape

### ISSUE THREAD

**Issue by VlaDexa** [scottrogowski/code2flow#33]
As per Russian standard for block-schemes, there is a shape for functions/methods defined elsewhere.
It looks like this in plain style: 
![изображение](https://user-images.githubusercontent.com/52157081/136285445-21b59c91-d35b-4481-b7c1-7631cfded9dd.png)

I'll try to take a look at the code on my free time, but will promise nothing

**Comment by VlaDexa** [comment]
Maybe something like an option to change a style

**Comment by VlaDexa** [comment]
There is an ISO 5807:1985 standart for shapes for flow charts.
Sadly, I found only [this shortened document](https://www.figma.com/community/file/874638125262621876) on figma.
I use your program to help me with my university assigments

**Comment by scottrogowski** [comment]
I'm unfortunately going to close this. The use case wasn't quite compelling enough to warrant a change. Sorry.
