### ISSUE TITLE
Request: Output all call sites which refer to a given function

### ISSUE THREAD

**Issue by jasiek** [scottrogowski/code2flow#41]
Scenario: I have a method (ruby) defined in a model somewhere. I'd like to identify all call sites which call this method and call sites that refer to those call sites up to some given limit. This sounds like a subset of the graph which is generated.

**Comment by scottrogowski** [comment]
This has been something I’ve been thinking about given code2flow’s recent popularity boost. The graphs quickly get unwieldy past 100 functions or so and could be made more useful by limiting their scope in the way you describe. 

On the CLI I don’t know how this could be implemented elegantly. Adding a parameter for an exact name match of the function of interest might work… but it feels like doing this with a GUI would be a better approach. It also feels like a GUI is almost inevitable if the project is to evolve. 

Would be curious if you had more thoughts as well. The more useful the tool is for actual development - the better

**Comment by jasiek** [comment]
Yeah, exactly - or the ability to prune nodes that end up as calls into frameworks, etc. 

I think having this call graph representation and the ability to query it would be super useful for other stuff like a GUI, or an LSP-speaking server that'd plug into code editors, etc. Rolling this parse/store/analyze capability into a library would make it reusable from other places.

If this becomes the case and you have to analyse large amounts of code, some kind of a representation on disk might come handy - to be updated incrementally only when some of the code changes.

Anyway - I'm going to look into this call-graph subgraph thing to see if I can come up with anything useful.

**Comment by scottrogowski** [comment]
Shouldn’t be too tricky. I think it would be basically the last step before outputting results. Then it would be nice to have both upstream and downstream number of nodes as CLI args. Let me know if you wanted to take a stab at it. Otherwise will maybe do it myself in a few days. It’s a good idea.

**Comment by andheiberg-babylonhealth** [comment]
👍 I have the same need 😄 

Yeah a UI would be an elegant solution but specifying a function or class name with an optional depth parameter would probably solve most use cases.

This could in-deed be done as a post processing step. Was looking into how I could do this filtering on dot files. But obviously direct support in code2flow would be even better.

Vaguely interesting things I found related to this:

- [Filtering dot files (1)](https://github.com/seamia/filterdot)
- [Filtering dot files (2)](https://github.com/aarontan-git/dot_search)
- [Dot file GUI](http://manpages.ubuntu.com/manpages/bionic/man1/xdot.1.html)
- [Graph awk like utility]https://linux.die.net/man/1/gvpr

**Comment by scottrogowski** [comment]
I actually just started working on the feature - lest anyone else accidentally replicate my work. The work in progress has three new parameters:

- --target-function
- --upstream-depth
- --downstream-depth

I don't feel great about the names so would be curious if anyone has better suggestions. Also whether there is anything I am overlooking with that basic interface.

**Comment by scottrogowski** [comment]
PR open. If anyone could take a look it would be helpful. Otherwise, will merge and release in a few days. https://github.com/scottrogowski/code2flow/pull/44

**Comment by jasiek** [comment]
I'll give it a spin tomorrow.

**Comment by scottrogowski** [comment]
Went ahead and merged. Please do suggest anything else that could make it better. Thanks for the suggestion!
