### ISSUE TITLE
[Feature Request] Call code2flow from code

### ISSUE THREAD

**Issue by GameDungeon** [scottrogowski/code2flow#45]
Is it possible to run code2flow from code? In a library of mine, I'm adding a callgraph sphinx directive for embedding graphs in docs. My issue is I have to use something like subprocess to run to generate the graph, and that's a horrible solution.

**Comment by scottrogowski** [comment]
This is possible to some extent

    import code2flow
    code2flow.code2flow(['path/to/filea', 'path/to/fileb'], 'path/to/outputfile')

Those are the two required parameters. `code2flow.code2flow` has basically all of the same arguments as the CLI.

It's a little awkward to work with file path strings in a library interface so I would be open to suggestions for how to make the interface cleaner.

**Comment by GameDungeon** [comment]
Ah. I would add this to whatever you're using as docs. I'll make any suggestions I think of :)

**Comment by scottrogowski** [comment]
Added a small section to the docs
