### ISSUE TITLE
how to save the code to generate the flowchart

### ISSUE THREAD

**Issue by addy1997** [scottrogowski/code2flow#51]
Hello,

I mean to ask what extension like `.py` or `.cpp` is used to save the code?

Thanks

**Comment by scottrogowski** [comment]
Not sure I follow. It is saved in an intermediate form as a .gv (graphviz) file and then usually it is saved as an image of some kind. It depends on the command line arguments you pass. There is more info if you run 

    code2flow --help

**Comment by scottrogowski** [comment]
If I might offer a different interpretation, if you are trying to process a python file, you just do:

    code2flow path/to/python/file.py

If for some reason you have a different extension, you can also do something like

    code2flow path/to/python/directory/or/file --language py

**Comment by addy1997** [comment]
> If I might offer a different interpretation, if you are trying to process a python file, you just do:
> 
> ```
> code2flow path/to/python/file.py
> ```
> 
> If for some reason you have a different extension, you can also do something like
> 
> ```
> code2flow path/to/python/directory/or/file --language py
> ```

Thanks @scottrogowski. That's what I was asking.
