### ISSUE TITLE
'class fields' in js not supported

### ISSUE THREAD

**Issue by dhlolo** [scottrogowski/code2flow#53]
'class fields' is common in es6. But it should use [acorn plugin](https://stackoverflow.com/questions/65325260/acorn-why-arrow-function-throws-parsing-error), there seems no acorn plugin command line option~
![image](https://user-images.githubusercontent.com/50065494/156908392-ff137a44-4da7-43fe-925e-5e4832e307ca.png)

**Comment by scottrogowski** [comment]
I believe what you are looking for is:

    --source-type=module

Let me know if that works or if I misunderstood something.

**Comment by dhlolo** [comment]
> I believe what you are looking for is:
> 
> ```
> --source-type=module
> ```
> 
> Let me know if that works or if I misunderstood something.

Actually, 'class fields' is a feature that is not included in '--source-type=module'. I noticed the feature needs [acorn(javascript AST analyzer) plugin](https://stackoverflow.com/a/65325437) to enable the feature, rather than only acorn basic commands. However, I don't know make it through.

Maybe you can try:
`
   class A {
     // this will work.
     methodWork() {}
     // It doesn't work as 'class fields' feature.
     methodNotWork = () => {}
   }
`

**Comment by scottrogowski** [comment]
Reopening to investigate

**Comment by scottrogowski** [comment]
I'm understanding the problem better now. Class fields, owing to their newness, are not supported by vanilla acorn and need a plugin. I've confirmed that adding the plugin allows the parser to work whereas there was a syntax error previously. 

I'm reluctant to fix this. Using class fields for function definitions doesn't seem common enough to introduce another dependency that would complicate backward compatibility and keep the CLI clean. So I'll have to close this again. Feel free to protest if you think it is, actually, really common
