### ISSUE TITLE
Python 3 support.

### ISSUE THREAD

**Issue by prashnts** [scottrogowski/code2flow#7]
This module does not supports Python version 3, (or, so it seems). This is nowhere mentioned.

**Comment by gustavklopp** [comment]
+1

**Comment by HishamKamal** [comment]
Hi
I added python3 support. I could not submit it to this rep, but it is upload and open to download from my fork. 
https://github.com/HishamKamal/code2flow/tree/Python3.0Version

**Comment by PrashntS** [comment]
@HishamKamal why don't you open a PR?

**Comment by HishamKamal** [comment]
Not sure what PR stands for ?!

**Comment by dixudx** [comment]
@HishamKamal PR means Pull Request

**Comment by HishamKamal** [comment]
Done, thanks.

**Comment by scottrogowski** [comment]
I just closed the Python3 PR given that I ended up doing a rewrite of the project. I feel deeply sorry I didn't see this at the time. The rewrite does support Python3 so I think the issue is now addressed.
