### ISSUE TITLE
python setup.py egg_info did not run successfully.

### ISSUE THREAD

**Issue by dazui20** [scottrogowski/code2flow#72]
![image](https://user-images.githubusercontent.com/116625414/198812420-f7a9f79d-8497-4fd7-86b1-f6d8ffc5fc97.png)

**Comment by spliffli** [comment]
This is still not fixed, at least on manjaro linux. 
![Screenshot from 2023-08-21 14-56-12](https://github.com/scottrogowski/code2flow/assets/34756063/8a43df50-6f03-41c9-953a-cd3e10a49fc2)

**Comment by scottrogowski** [comment]
Hi @spliffli,

This is a different error and appears to be related to your local environment. This might help: https://github.com/pypa/packaging-problems/issues/573#issuecomment-1040587425. You're also welcome to try `python3 --version`. I just tested with a fresh 3.10 installation and everything still seems to work but it's possible that in some very old versions of Python you get this error.
