### ISSUE TITLE
wrong line number?

### ISSUE THREAD

**Issue by ckhung** [scottrogowski/code2flow#9]
Hi Scott, thanks for this nice tool.

The line numbers seem to be incorrect.
For example, from this code:
https://github.com/ckhung/d3-stat-map/blob/master/main.js
code2flow generates this graph (slightly manually edited):
https://github.com/ckhung/d3-stat-map/blob/master/call-graph.svg

I tried removing comments but it doesn't seem to be the cause.

**Comment by scottrogowski** [comment]
Hey Ckhung. This is incredibly old but I'm making it a point to go through old issues. I just merged a Python rewrite which now uses AST so I suspect the line number issue will have been fixed.
